/* 
 * Copyright (C) 2014 Marc Segond <dr.marc.segond@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.marsouin.data;

import java.io.IOException;
import ucar.nc2.*;
import ucar.ma2.*;
import java.util.Date;
import java.util.GregorianCalendar;


public class OpenNetCdfBatch extends javax.swing.JDialog {
    
    private int[] prof=null;
    
    /** Creates new form OpenNetCdfBatch */
    public OpenNetCdfBatch(java.awt.Frame parent, boolean modal,String n) {
        super(parent, modal);
        initComponents();
        lireNetCDF(n);
        this.setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        profsDispos = new javax.swing.JList();
	profsDispos.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
	profsDispos.setSelectedIndex(0);
        ok = new javax.swing.JButton();
	jScrollPane1 = new javax.swing.JScrollPane();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
	jScrollPane1.setViewportView(profsDispos);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okPressed(evt);
            }
        });

	

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(ok, gridBagConstraints);


	setSize(250,200);

    }//GEN-END:initComponents

    private void okPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okPressed
        prof = profsDispos.getSelectedIndices();
        setVisible(false);
        dispose();
    }//GEN-LAST:event_okPressed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        prof = profsDispos.getSelectedIndices();
        setVisible(false);
        dispose();
    }//GEN-LAST:event_exitForm
    
    public int[] getProf(){return prof;}
    
    public final void lireNetCDF(String s){
        try{
         NetcdfFile f = NetcdfFile.open(s);
         
         Variable var = f.findVariable("time");
         Array tps = var.read();
         String[] times = new String[tps.getShape()[0]];
         Index ind = tps.getIndex();
         for(int i=0;i<(tps.getShape())[0];i++){
            ind.set(i);
            double t = tps.getDouble(ind);
            System.out.println("temps : "+t);
            long tmp = (long)t;
            System.out.println("temps : "+tmp);
            GregorianCalendar cal = new GregorianCalendar(1900,0,1,0,0,0);
            Date ref = cal.getTime();
            tmp = tmp * 1000;
            tmp = tmp + ref.getTime();
            Date cur = new Date(tmp);
            
            times[i]=cur.toString();
         }
         profsDispos.setListData(times);
         f.close();
         System.gc();
        }catch(IOException e){System.out.println(e.getMessage());}
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ok;
    private javax.swing.JList profsDispos;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
