/*
 * FrmVisual.java
 *
 * Created on 3 septembre 2004, 18:14
 */


package visu;

import java.io.File;
import data.SimpleSaxParser;

/**
 *
 * @author  Marc Segond
 */
public final class FrmConf extends javax.swing.JFrame implements constants.centre, constants.couleur, constants.balise, constants.fourmi, constants.streamlines{
    
    private Memoire mem = null;
    
    /** Creates new form FrmVisual */
    public FrmConf() {
        initConfFile();
        initComponents();
    }
    
    public FrmConf(Memoire m, boolean Ok3D) {
        initComponents();
        mem = m;
        initConfFile();
        if(!Ok3D)
        javax.swing.JOptionPane.showMessageDialog(this,"Java3D was not detected on your system. 3D visualization will not be available.\nTo download Java3D: http://java.sun.com/products/java-media/3D/","Marsouin v3.1.0",javax.swing.JOptionPane.INFORMATION_MESSAGE,new javax.swing.ImageIcon(this.getIconImage()));
    }
    
    @Override
    public java.awt.Image getIconImage(){
        return(new javax.swing.ImageIcon("logo_carre.gif").getImage());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNbFourmisDistinctes = new javax.swing.JTextField();
        NbFourmisParEspeceTextfield = new javax.swing.JTextField();
        jTextFieldNbGen = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldDepotPheromone = new javax.swing.JTextField();
        jTextFieldCoeffEvap = new javax.swing.JTextField();
        jTextFieldBiais = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldNbRechParCarte = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldStreamSeuilBouclage = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldStreamSeuilPointCritique = new javax.swing.JTextField();
        jTextFieldStreamPrecision = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jCheckBoxUseMethodFourmi = new javax.swing.JCheckBox();
        jCheckBoxUseMethodStreamlines = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFichier = new javax.swing.JMenu();
        jMenuItemOuvrir = new javax.swing.JMenuItem();
        jMenuInfo = new javax.swing.JMenu();
        jMenuItemInfo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Marsouin v3.0");
        setIconImage(getIconImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel4.setText("Number of colonies:");
        jPanel3.add(jLabel4, new java.awt.GridBagConstraints());

        jLabel5.setText("Number of ants in a colony:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel3.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Number of iterations:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel3.add(jLabel6, gridBagConstraints);

        jTextFieldNbFourmisDistinctes.setText("5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(jTextFieldNbFourmisDistinctes, gridBagConstraints);

        NbFourmisParEspeceTextfield.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(NbFourmisParEspeceTextfield, gridBagConstraints);

        jTextFieldNbGen.setText("500");
        jTextFieldNbGen.setMinimumSize(new java.awt.Dimension(35, 19));
        jTextFieldNbGen.setPreferredSize(new java.awt.Dimension(35, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(jTextFieldNbGen, gridBagConstraints);

        jLabel7.setText("Amount of pheromone dropped:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel3.add(jLabel7, gridBagConstraints);

        jLabel8.setText("Evaporation rate:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel3.add(jLabel8, gridBagConstraints);

        jLabel9.setText("Maximum directionnal bias:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        jPanel3.add(jLabel9, gridBagConstraints);

        jTextFieldDepotPheromone.setText("10");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(jTextFieldDepotPheromone, gridBagConstraints);

        jTextFieldCoeffEvap.setText("0.1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(jTextFieldCoeffEvap, gridBagConstraints);

        jTextFieldBiais.setText("45");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(jTextFieldBiais, gridBagConstraints);

        jLabel10.setText("Number of detections per map:");
        jLabel10.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel3.add(jLabel10, gridBagConstraints);

        jTextFieldNbRechParCarte.setText("4");
        jTextFieldNbRechParCarte.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(jTextFieldNbRechParCarte, gridBagConstraints);

        jTabbedPane1.addTab("Ants parameters", null, jPanel3, "M\u00e9thodes fourmis");

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Looping threshold:");
        jPanel1.add(jLabel1, new java.awt.GridBagConstraints());

        jTextFieldStreamSeuilBouclage.setText("0.2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel1.add(jTextFieldStreamSeuilBouclage, gridBagConstraints);

        jLabel2.setText("Critical point threshold:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Precision:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel1.add(jLabel3, gridBagConstraints);

        jTextFieldStreamSeuilPointCritique.setText("0.2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel1.add(jTextFieldStreamSeuilPointCritique, gridBagConstraints);

        jTextFieldStreamPrecision.setText("1.0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel1.add(jTextFieldStreamPrecision, gridBagConstraints);

        jTabbedPane1.addTab("Streamlines parameters", null, jPanel1, "M\u00e9thode math\u00e9matique \u00e0 base de streamlines");

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        jCheckBoxUseMethodFourmi.setSelected(true);
        jCheckBoxUseMethodFourmi.setText("Ant based detection");
        jCheckBoxUseMethodFourmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxUseMethodFourmiActionPerformed(evt);
            }
        });

        jPanel2.add(jCheckBoxUseMethodFourmi);

        jCheckBoxUseMethodStreamlines.setText("Streamlines based detection");
        jPanel2.add(jCheckBoxUseMethodStreamlines);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        jMenuFichier.setText("File");
        jMenuItemOuvrir.setText("Open File");
        jMenuItemOuvrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOuvrirActionPerformed(evt);
            }
        });

        jMenuFichier.add(jMenuItemOuvrir);

        jMenuBar1.add(jMenuFichier);

        jMenuInfo.setText("?");
        jMenuInfo.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jMenuItemInfo.setText("About");
        jMenuItemInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afficherInfos(evt);
            }
        });

        jMenuInfo.add(jMenuItemInfo);

        jMenuBar1.add(jMenuInfo);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxUseMethodFourmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxUseMethodFourmiActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxUseMethodFourmiActionPerformed
    
    private void afficherInfos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afficherInfos
        javax.swing.JOptionPane.showMessageDialog(this,"Marsouin v3.1.0\nCopyright LIL/ULCO\nMarc Segond, Cyril Fonlupt, Denis Robilliard\nContact: segond@lil.univ-littoral.fr\nWeb Page: http://www-lil.univ-littoral.fr/~segond/EN/Marsouin.html","Marsouin v3.1.0",javax.swing.JOptionPane.INFORMATION_MESSAGE,new javax.swing.ImageIcon(getIconImage()));
    }//GEN-LAST:event_afficherInfos
    
    private void jMenuItemOuvrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOuvrirActionPerformed
        String cheminDefaut;
        
        if(mem.getMemCheminExplo() != null)
            cheminDefaut = mem.getMemCheminExplo();
        else
            cheminDefaut = System.getProperty("user.home");
        
        javax.swing.JFileChooser F = new javax.swing.JFileChooser(cheminDefaut);
        
        F.setDialogTitle("Choose a NetCDF file");
        F.setMultiSelectionEnabled(false);
        
        int returnVal=F.showOpenDialog(this);
        File fichs=null;
        try{
            if(returnVal == javax.swing.JFileChooser.APPROVE_OPTION){
                fichs = F.getSelectedFile();
                mem.setMemCheminExplo(F.getCurrentDirectory().getAbsolutePath());
                if(fichs!=null){
                    mem.ajoutCarte(fichs.getAbsolutePath());
                }else
                    System.out.println("Noms de fichiers = null");
            }
        }catch(Exception e){ System.out.println(" FrmConf : erreur d'ouverture de carte :"+e.toString());}
    }//GEN-LAST:event_jMenuItemOuvrirActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        SaveParams();
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    private void initConfFile(){
        try{
            File homeDir, configDir, configFile;
            String userHome = System.getProperty("user.home");
            homeDir = new File(userHome);
            if ((homeDir==null)||(!homeDir.isDirectory()))
                throw new Exception("homeDir is no dir");
            configDir = new File(homeDir,CONFIG_DIR);
            //System.out.println("repertoire configuration...");
            if (configDir.mkdir())
                System.out.println("Creation of "+configDir.getAbsolutePath() );
            System.out.println("Entering config directory...");
            configFile = new File(configDir,CONFIG_FILE);
            if(configFile.createNewFile()){
                System.out.println("New conf file ceated");
                data.writeTextFile wtf = new data.writeTextFile(configFile.getAbsolutePath());
                wtf.uneLigne("<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>");
                wtf.uneLigne("<fourmis nbfourm=\"4\" nbgen=\"500\"  nbcolo=\"5\" depot=\"5.0\" evap=\"10.0\" biais=\"60.0\"></fourmis>");
                wtf.fermer();
            }
            SimpleSaxParser parser = new SimpleSaxParser(this);
            parser.parse(configFile.getAbsolutePath());
            
        }catch(Exception e){ System.out.println(e.toString());}
    }
    
    private void SaveParams(){
        try{
            File homeDir, configDir, configFile;
            String userHome = System.getProperty("user.home");
            homeDir = new File(userHome);
            if ((homeDir==null)||(!homeDir.isDirectory()))
                throw new Exception("homeDir is no dir");
            configDir = new File(homeDir,CONFIG_DIR);
            System.out.println("Entering config directory...");
            configFile = new File(configDir,CONFIG_FILE);
            System.out.println("Saving config");
            data.writeTextFile wtf = new data.writeTextFile(configFile.getAbsolutePath());
            wtf.uneLigne("<?xml version=\"1.0\" encoding=\"ISO-8859-1\" ?>");
            wtf.uneLigne("<fourmis nbfourm=\""+getFourmiNB()[FOURMI_NB_INTRA_ESPECE]+"\" nbgen=\""+getFourmiNB()[FOURMI_NB_GENERATIONS]+"\"  nbcolo=\""+getFourmiNB()[FOURMI_NB_ESPECES]+"\" depot=\""+getFourmiCoeff()[FOURMI_QTE_DEPOT]+"\" evap=\""+getFourmiCoeff()[FOURMI_COEFF_EVAPORATION]+"\" biais=\""+getFourmiCoeff()[FOURMI_TAUX_COURBURE]+"\"></fourmis>");
            wtf.fermer();
            System.out.println("Config saved");
        }catch(Exception e){ System.out.println(e.toString());}
    }
    
    public void setUseMethod(final boolean[] tb) {
        jCheckBoxUseMethodFourmi.setSelected(tb[USE_METHOD_FOURMI]);
        jCheckBoxUseMethodStreamlines.setSelected(tb[USE_METHOD_STREAMLINES]);
    }
    
    public void setFourmiCoeff(final double[] tb) {
        jTextFieldCoeffEvap.setText(Double.toString(tb[FOURMI_COEFF_EVAPORATION]));
        jTextFieldDepotPheromone.setText(Double.toString(tb[FOURMI_QTE_DEPOT]));
        jTextFieldBiais.setText(Double.toString(tb[FOURMI_TAUX_COURBURE]));
    }
    
    public void setEvap(double  tb) {
        double[] temp = getFourmiCoeff();
        temp[FOURMI_COEFF_EVAPORATION]=tb;
        setFourmiCoeff(temp);
    }
    
    public void setBiais(double  tb) {
        double[] temp = getFourmiCoeff();
        temp[FOURMI_TAUX_COURBURE]=tb;
        setFourmiCoeff(temp);
    }
    
    public void setDepot(double  tb) {
        double[] temp = getFourmiCoeff();
        temp[FOURMI_QTE_DEPOT]=tb;
        setFourmiCoeff(temp);
    }
    
    public void setStreamlinesParam(final double[] tb) {
        jTextFieldStreamSeuilBouclage.setText(Double.toString(tb[STREAM_SEUIL_BOUCLAGE]));
        jTextFieldStreamSeuilPointCritique.setText(Double.toString(tb[STREAM_SEUIL_POINT_CRITIQUE]));
        jTextFieldStreamPrecision.setText(Double.toString(tb[STREAM_PRECISION]));
    }
    
    public void setFourmiNB(final int[]  tb) {
        jTextFieldNbGen.setText(Integer.toString(tb[FOURMI_NB_GENERATIONS]));
        jTextFieldNbFourmisDistinctes.setText(Integer.toString(tb[FOURMI_NB_ESPECES]));
        NbFourmisParEspeceTextfield.setText(Integer.toString(tb[FOURMI_NB_INTRA_ESPECE]));
    }
    
    public void setNbGen(int  tb) {
        int[] temp = getFourmiNB();
        temp[FOURMI_NB_GENERATIONS]=tb;
        setFourmiNB(temp);
    }
    
    public void setNbFourmis(int  tb) {
        int[] temp = getFourmiNB();
        temp[FOURMI_NB_INTRA_ESPECE]=tb;
        setFourmiNB(temp);
    }
    
    public void setNbColo(int  tb) {
        int[] temp = getFourmiNB();
        temp[FOURMI_NB_ESPECES]=tb;
        setFourmiNB(temp);
    }
    
    public final int[] getFourmiNB() {
        int[] tb = new int[LENGTH_FOURMI_NB];
        tb[FOURMI_NB_GENERATIONS]=Integer.parseInt(jTextFieldNbGen.getText());
        tb[FOURMI_NB_ESPECES]=Integer.parseInt(jTextFieldNbFourmisDistinctes.getText());
        tb[FOURMI_NB_INTRA_ESPECE]=Integer.parseInt(NbFourmisParEspeceTextfield.getText());
        tb[FOURMI_NB_RUNS]=Integer.parseInt(this.jTextFieldNbRechParCarte.getText());
        return tb;
    }
    
    public final boolean[] getUseMethod() {
        boolean[] tb = new boolean[LENGTH_USE_METHOD];
        tb[USE_METHOD_FOURMI]=jCheckBoxUseMethodFourmi.isSelected();
        tb[USE_METHOD_STREAMLINES]=jCheckBoxUseMethodStreamlines.isSelected();
        return tb;
    }
    
    public final boolean[] getFourmiBAff() {
        boolean[] tb = new boolean[LENGTH_FOURMI_BAFF];
        return tb;
    }
    
    public final double[] getFourmiCoeff() {
        double[] tb = new double[LENGTH_FOURMI_COEFF];
        tb[FOURMI_COEFF_EVAPORATION]=Double.parseDouble(jTextFieldCoeffEvap.getText());
        tb[FOURMI_QTE_DEPOT]=Double.parseDouble(jTextFieldDepotPheromone.getText());
        tb[FOURMI_TAUX_COURBURE]=Double.parseDouble(jTextFieldBiais.getText());
        return tb;
    }
    
    public final double[] getStreamParams() {
        double[] tb = new double[LENGTH_STREAMLINES_PARAM];
        tb[STREAM_SEUIL_BOUCLAGE]=Double.parseDouble(jTextFieldStreamSeuilBouclage.getText());
        tb[STREAM_SEUIL_POINT_CRITIQUE]=Double.parseDouble(jTextFieldStreamSeuilPointCritique.getText());
        tb[STREAM_PRECISION]=Double.parseDouble(jTextFieldStreamPrecision.getText());
        return tb;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NbFourmisParEspeceTextfield;
    private javax.swing.JCheckBox jCheckBoxUseMethodFourmi;
    private javax.swing.JCheckBox jCheckBoxUseMethodStreamlines;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFichier;
    private javax.swing.JMenu jMenuInfo;
    private javax.swing.JMenuItem jMenuItemInfo;
    private javax.swing.JMenuItem jMenuItemOuvrir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldBiais;
    private javax.swing.JTextField jTextFieldCoeffEvap;
    private javax.swing.JTextField jTextFieldDepotPheromone;
    private javax.swing.JTextField jTextFieldNbFourmisDistinctes;
    private javax.swing.JTextField jTextFieldNbGen;
    private javax.swing.JTextField jTextFieldNbRechParCarte;
    private javax.swing.JTextField jTextFieldStreamPrecision;
    private javax.swing.JTextField jTextFieldStreamSeuilBouclage;
    private javax.swing.JTextField jTextFieldStreamSeuilPointCritique;
    // End of variables declaration//GEN-END:variables
    
}
