/*
 * VortexProperties.java
 *
 * Created on 1 mars 2005, 11:07
 */

package visu;

/**
 *
 * @author  segond
 */
public class VortexProperties extends javax.swing.JFrame {
    
    int numVortex = 0;
    String unit="";
    
    /** Creates new form ProprietesVortex */
    public VortexProperties() {
        initComponents();
    }
    
    @Override
    public java.awt.Image getIconImage(){
        return(new javax.swing.ImageIcon("logo_carre.gif").getImage());
    }
    
    public VortexProperties(int nb) {
        initComponents();
        numVortex = nb;
        this.setTitle("Properties of vortex "+numVortex+":");
    }
    
    public void setAire(double d){
        this.jLabelAireVortex.setText("Area: "+d);
    }
    
    public void setPeriode(double d){
        this.jLabelPeriode.setText("Period: "+d);
    }
    
    public void setRayonMoyen(double d){
        this.jLabelRayonMoyen.setText("Mean radius: "+d);
    }
    
    public void setCentre(double a, double b){
        this.jLabelCentre.setText("Center coordinates: "+a+"°E;"+b+"°N");
    }
    
    public void setUnit(String u){
        unit = u;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelAireVortex = new javax.swing.JLabel();
        jLabelRayonMoyen = new javax.swing.JLabel();
        jLabelPeriode = new javax.swing.JLabel();
        jLabelCentre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Propriétés Vortex");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabelAireVortex.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAireVortex.setText("AireVortex");
        jLabelAireVortex.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jLabelAireVortex, gridBagConstraints);

        jLabelRayonMoyen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRayonMoyen.setText("RayonMoyen");
        jLabelRayonMoyen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jLabelRayonMoyen, gridBagConstraints);

        jLabelPeriode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPeriode.setText("Periode");
        jLabelPeriode.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jLabelPeriode, gridBagConstraints);

        jLabelCentre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCentre.setText("Centre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jLabelCentre, gridBagConstraints);

        setSize(new java.awt.Dimension(515, 165));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAireVortex;
    private javax.swing.JLabel jLabelCentre;
    private javax.swing.JLabel jLabelPeriode;
    private javax.swing.JLabel jLabelRayonMoyen;
    // End of variables declaration//GEN-END:variables
    
}
